-- CREATE accounts TABLE
drop table if exists accounts;

create table accounts (
    id int generated by default as identity,
    name varchar(100) not null,
    balance dec(15,2) not null,
    primary key(id)
);

insert into accounts(name,balance)
values('Bob',10000);

insert into accounts(name,balance)
values('Alice',10000);


-- CREATE PROCEDURE TO TRANSFER MONNEY FROM SENDER TO RECIEVER
create or replace procedure transfer (
	IN sender int, 
	IN reciever int, 
	IN amount dec
)
language plpgsql
as $$
declare
begin
	
	-- substract 
	update accounts
	set balance = balance - amount
	where id = sender;
	
	-- plus
	update accounts
	set balance = balance + amount
	where id = reciever;
	
	COMMIT;
	
end;$$

-- CALL PROCEDURE
CALL transfer(1,2,5000) 

select * from accounts